#ifndef __DEVCMF_H_
#define __DEVCMF_H_

#define S485_UART_CMD_SET_TXBLOCK	1
#define S485_UART_CMD_CLR_TXBLOCK	2
#define S485_UART_CMD_SET_RXBLOCK	3
#define S485_UART_CMD_CLR_RXBLOCK	4
#define S485UART_SET_TXWAITTIME_MS	5
#define S485UART_SET_RXWAITTIME_MS	6


#endif
